### ISSUE TITLE
Commitlint

### ISSUE THREAD

**Issue by binjospookie** [Arkweid/lefthook#110]
Hi!
I want to use Lefthook with Commitlint on pre-commit.
In Commitlint's docs I found `"commit-msg": "commitlint -E HUSKY_GIT_PARAMS"` (https://github.com/conventional-changelog/commitlint#getting-started). But Lefthook hasn't `HUSKY_GIT_PARAMS` of course :)

What should I do to solve this problem?

**Comment by Arkweid** [comment]
Try it like usual executable you have:
commit-msg:
  commands:
    commitlint:
      run: echo "wololo" | commitlint

Or try it just like script:
https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#bash-script-example

**Comment by binjospookie** [comment]
Thank you! I'll try and update this issue with new information.

**Comment by binjospookie** [comment]
I modify your script with type-enum from https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum

Looks like:
```bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^(build|ci|docs|feat|fix|perf|refactor|revert|style|test)+: "
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo -e "Invalid commit message.\nCommit message must start with '(build|ci|docs|feat|fix|perf|refactor|revert|style|test):'"
  exit 1
fi
```

Thank you for help!
