### ISSUE TITLE
Deploying to Now by Zeit causes 128 error

### ISSUE THREAD

**Issue by muuvmuuv** [Arkweid/lefthook#112]
I'm hosting my website on [Now by Zeit](https://zeit.co/home). They have a [CI that pulls recently pushed changes](https://github.com/muuvmuuv/portfolio/pull/10#issuecomment-581965211), build my website and provide a development test url for me. I have added lefthook today and now seeing the below error. Lefthook is installed via a `package.json` postinstall script and I think this is the issue here because `.git` isn't available in the CI. I can not find any referrence for CI integrations with lefthook. Do I even need a `postinstall` command?

```
[4/4] Building fresh packages...
--
08:12:25 PM | success Saved lockfile.
08:12:25 PM | $ lefthook install
08:12:25 PM | exit status 128
08:12:25 PM | error Command failed with exit code 1.
08:12:25 PM | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
08:12:25 PM | Error: Exited with 1
08:12:25 PM | at ChildProcess.<anonymous> (/zeit/5a5e1dc84b69412d/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:33884:24)
08:12:25 PM | at ChildProcess.emit (events.js:210:5)
08:12:25 PM | at ChildProcess.EventEmitter.emit (domain.js:475:20)
08:12:25 PM | at maybeClose (internal/child_process.js:1021:16)
08:12:25 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
08:12:25 PM | worker exited with code 20 and signal null
08:12:28 PM | Done with "package.json"
```

**Comment by Arkweid** [comment]
Postinstall script checking standart `CI` env variable. Postinstall will be skipped if the variable is present. Try to add it
https://github.com/Arkweid/lefthook/blob/master/.npm/postinstall.js#L4

**Comment by muuvmuuv** [comment]
Yes, that worked! I also noticed that Now sets this env but I had postinstalled lefthook by my own in my package.json, which was the issue. I didn't know lefthook installs itself after installation :)
