### ISSUE TITLE
Halt if running hooks causes repo to become dirty

### ISSUE THREAD

**Issue by jlucktay** [Arkweid/lefthook#117]
First up, thank you for `lefthook`! It's very quick and handy.

My issue is that if any of the hook commands make changes to the repo contents, I think that the following action (e.g. tasks in the `pre-push` group relating to the git push) should be stopped.

I have looked through the documentation, the full guide, and the wiki, but I can't see a flag anywhere to control behaviour like this.

Is it currently depending solely on the exit status of the command/script?

Thanks again!

**Comment by Arkweid** [comment]
Hi @jlucktay 
Yes, it depends only on exit status from command/script. So good way for you case it just another exit status from your scripts if something was changed.

**Comment by jlucktay** [comment]
OK, thanks @Arkweid!
