### ISSUE TITLE
Вопросы для документации

### ISSUE THREAD

**Issue by ai** [Arkweid/lefthook#13]
1. Какие главные фичи проекта, которые модно показать в примере конфига? Я пока вижу:
    * Проверяем только изменённые файлы
    * Паралелльный запуск
    * Что ещё?
2. На какие рынки мы хотим зайти с конкретными инструкциями? То есть для чего мы хотим создавать обвязки и всякий сахар? Ruby и Node.js?
3. Что с банчмарками? С кем сравнивать? В Node.js главный Husky и Husky+lint-staged. Кто ещё наши конкуренты?
4. Я вижуу такие плюсы: быстрота (на Go, не создаём левые скрипты в `.git/hooks`), гибкость (там пару примеров которые очень сложно сделать без lefthook), простота (установки и развёртывания? Ибо один бинарник и сахар)
5. Какие примеры хитрых настроек, которые делали пользователи? Вот «Перед пушем прогонять через линтер только те файлы что изменились». Что ещё?

@Arkweid

**Comment by HellSquirrel** [comment]
1. 
Первая фича -- гибкость! Можно настроить любой, даже самый извращенный флоу
Вторая фича -- замена хаски ^^
2. Я думаю любой рынок где есть (lint-staged) и может что-то еще
3. Бенчмарки вообще сомнительные. Тормозит обычно не тулза, а те процессы которые на прекомит-хук отрабатывают
4. +
5. Может какие-то сценарии, связанные с git-flow. Например делать что-то особенное при мерже в мастер?)

**Comment by ai** [comment]
«При мерже веток прогоняем линтер и тесты тех файлов что изменились». Норм? А это можно написать меньше чем в 10 строк? Или мы сможем дать сниппет.

**Comment by Arkweid** [comment]
1. Можем запускать кастомные скрипты, а не только one-line-command. Можно адаптировать окружение(актуально для тех кто работает через докер). Есть интерактивность - т.е. если скрипт запросит что-то на ввод, то это все работает. Актуально для всяких проверок соответствия шаблону коммита.
2. Я думаю этих двух будет достаточно.
3. Я не очень в курсе этих двух инструментов. На руби это overcommit. Но у нас есть параллельность и уничтожение кучи зависимостей в node_modules.
5. Закидывали в `files:` кастомный скрипт, который по очень замороченной логике отдавал список файлов для проверки. В руби пример как моженить с crystallball(определяет по каким файлам нужно прогнать тесты)

**Comment by palkan** [comment]
1. Фичи:
- Локальный override конфига под персональные нужды (поменять runner, отключить часть проверок (беку — бековое, фронту — фронтовое)
- Тэги для хуков

**Comment by ai** [comment]
А что такое теги для хуков?

**Comment by palkan** [comment]
Вот пример:

```
pre-commit:
  commands:
    rubocop:
      tags: backend
      glob: "**/*.rb"
      runner: bundle exec rubocop --safe-auto-correct {staged_files} && git add {staged_files}
```

Можно отключить проверку локально (добавив `exclude: - backend` в `.lefthook.local`), либо для конкретного запуска (`LEFTHOOK_EXCLUDE=backend git push`).
