### ISSUE TITLE
Can't retrieve arguments

### ISSUE THREAD

**Issue by nesk** [Arkweid/lefthook#133]
I need to create a `post-checkout` hook to compare the old `HEAD` to the new one.

I've installed lefthook through `brew install Arkweid/lefthook/lefthook` (v0.7.2) and created this configuration:

```
post-checkout:
  commands:
    test:
        run: echo $1 $2 $3
```

I expect the positional arguments to contain [the values provided by the hook](https://git-scm.com/docs/githooks#_post_checkout):

> The hook is given three parameters: the ref of the previous HEAD, the ref of the new HEAD (which may or may not have changed), and a flag indicating whether the checkout was a branch checkout (changing branches, flag=1) or a file checkout (retrieving a file from the index, flag=0).

However, when running `lefthook run post-checkout val1 val2 val3`, the output is empty.

I'm not sure if this is a bug or if I'm doing something wrong?

**Comment by vaporyhumo** [comment]
The positional arguments are only passed down to scripts aparently.
Take a look here https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#bash-script-example
