### ISSUE TITLE
Automatically linting docker containers by using lefthook

### ISSUE THREAD

**Issue by nitzano** [Arkweid/lefthook#138]
Hi there, 

I've recently wrote an article about solving the problem of linting docker containers and lefthook was my main (and favorite ⭐) solution:

https://dev.to/nitzano/linting-docker-containers-2lo6

If you find it relevant feel free to add it to the articles section at end of  README.md  :)

Nitzan

**Comment by Arkweid** [comment]
Awesome!
Done: https://github.com/Arkweid/lefthook/blob/master/README.md#articles

**Comment by nitzano** [comment]
> Awesome!
> Done: https://github.com/Arkweid/lefthook/blob/master/README.md#articles

@Arkweid: Thank you! :)
