### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by TheBlackArroVV** [Arkweid/lefthook#29]
Is it real to setup a global config in my user root and directory and use the same config for all my projects?

**Comment by Arkweid** [comment]
Can you tell what goal you are trying to achieve? All you projects have the same hooks/lints/settings? And you don't want to have this config in project repository for other team members?

**Comment by TheBlackArroVV** [comment]
I have few pet projects on which i work alone and where i use the same rules
So, i would like to get same global config, which achieve main rules, which can be rewrited in specific directory

**Comment by Arkweid** [comment]
Okay. Sounds like case for _symbolic links_.
https://www.shellhacks.com/symlink-create-symbolic-link-linux/
1. Go to you home directory and create a general `lefthook.yml` with desired configuration.
2. Go to you project directory and make a link
```
ln -s ~/lefthook.yml ./lefthook.yml
```
3. Rewrite general configuration by `lefthook-local.yml` with specific settings.

Lefthook doesn't support general configuration, so I think it's only way to achieve your goal.

**Comment by TheBlackArroVV** [comment]
Thanks
