### ISSUE TITLE
Lefhook config in dependencies

### ISSUE THREAD

**Issue by marapper** [Arkweid/lefthook#30]
We want to have lefthook in some library and use node_modules/@some/package/.lefthook.yml as a base config. 

It would be great if we could add some parameters in package.json

or use something like inheritance in yaml like

    # lefthook.yml
    extends: @some/package/.lefthook.yml

**Comment by Arkweid** [comment]
Make sense. I will add in the next version.

**Comment by Arkweid** [comment]
Done: https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#extends-option

**Comment by marapper** [comment]
Thanks!
