### ISSUE TITLE
Incorrect logging in console (windows)

### ISSUE THREAD

**Issue by sochisic** [Arkweid/lefthook#31]
Result of execution in windows bash. Please take a look below 
Looks like issue like there [https://github.com/rs/zerolog/issues/153](https://github.com/rs/zerolog/issues/153)
Can you check it?

```
$ lefthook run pre-commit
?[36mRUNNING HOOKS GROUP:?[0m ?[1mpre-commit?[0m
?[36m
  EXECUTE >?[0m ?[1mtests?[0m
?       github.com/sochisic/tg-retard-jokes-bot [no test files]
?[36m
SUMMARY: (done in 2.15 seconds)?[0m
✔️  ?[32mtests?[0m
```

**Comment by Arkweid** [comment]
Do you use terminal from Ubuntu sybsytem on Windows? Or some kind of emulators, [cygwin](https://cygwin.com/) for example?

**Comment by sochisic** [comment]
I didn't use go in wsl mode but I think there all will be good

**Comment by Arkweid** [comment]
https://cdn1.savepice.ru/uploads/2019/7/30/29ead40b0dcc6f9e0f380bed54902552-full.png

Checked.
As expected, default terminal with enabled `wsl` mode just have an issue with emoji. But who use default terminal? :D Maybe at winter 2019 they release [terminal 2.0](https://github.com/microsoft/terminal) 
MinTTY(just first unix-like terminal emulator I found for test) works well. Emoji interpreted right.

**Comment by sochisic** [comment]
I used git bash(mintty) not cmd or powershell. Let's wait they start to perform standarts, for me it isn't big problem anyway.
![image](https://user-images.githubusercontent.com/23560931/62087746-82f74a00-b26b-11e9-9d70-a82c9e04c3b6.png)
