### ISSUE TITLE
snap version haven't access to git commands

### ISSUE THREAD

**Issue by gsmendoza** [Arkweid/lefthook#34]
Hello! 

Appreciate if you can help me troubleshoot this issue I'm having. I'm trying to set up lefthook on my repo. So far, the pre-commit hook is returning "SKIP. NO FILES FOR INSPECTING" message even though there are staged files ready for commit. Please see below a description of the issue. Let me know if there's any other information you need! Thanks!

## Expected behavior

Given I have a git repo with a single file: a `lefthook.yml` config:

```
pre-commit:
  commands:
    hello_world:
      run: echo 'hello world!'
```

And I have installed lefthook like so:

```
sudo snap install --devmode lefthook
lefthook install
```

When I run `echo 'test' > text.txt && git add -A && lefthook run pre-commit`

Then I should see "hello world!"

## Actual behavior

```
lefthook-test 18:03:06 $ echo 'test' > text.txt && git add -A && lefthook run pre-commit
Lefthook v0.6.3
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > hello_world
(SKIP. NO FILES FOR INSPECTING)

SUMMARY: (SKIP EMPTY)
```

**Comment by Arkweid** [comment]
That happens because you have a fresh repo. So `git ls-files` return nothing.
Two ways to fix that:
1. Commit some files into the repo.
Or
2. Change a config like this:
pre-commit:
  commands:
    hello_world:
      skip_empty: false
      run: echo 'hello world!'

**Comment by gsmendoza** [comment]
Hello @Arkweid! I've committed lefthook.yml, so `git ls-files` now returns:

```
lefthook-test 19:17:59 $ git ls-files 
lefthook.yml
```

However, `echo 'test' > text.txt && git add -A && lefthook run pre-commit` still returns "(SKIP. NO FILES FOR INSPECTING)".

**Comment by Arkweid** [comment]
Looks like a bug with snap version. For some reason it changes current working directory. I will inspect it more close later. Thank you for this report!

**Comment by gsmendoza** [comment]
I see. I'll use the `go` version then. Thanks!

**Comment by Arkweid** [comment]
The problem tied with snap restriction policy and not allow to have and access to `git`.
`snap` version hided from docs and waiting a patch.

**Comment by Arkweid** [comment]
Snap version irrelevant for now.
