### ISSUE TITLE
Fixers do not stop commits

### ISSUE THREAD

**Issue by asottile** [Arkweid/lefthook#58]
Here's a trivial example:

```dockerfile
FROM ubuntu:bionic
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        python3-pip \
        python3-setuptools \
    && apt-get clean
RUN : \
    && curl --location --silent --output /tmp/lefthook.gz https://github.com/Arkweid/lefthook/releases/download/v0.6.3/lefthook_0.6.3_Linux_x86_64.gz \
    && echo '0876ae7a862cb26aa5bd50173502dfd836cd16317f7af18be0797deeb3e1cfcd  /tmp/lefthook.gz' | sha256sum --check \
    && gunzip /tmp/lefthook.gz \
    && mv /tmp/lefthook /usr/local/bin \
    && chmod +x /usr/local/bin/lefthook \
    && which lefthook

RUN pip3 install autopep8
        
WORKDIR /src

COPY lefthook.yml .

ENV \
    GIT_AUTHOR_EMAIL=a@example.com \
    GIT_AUTHOR_NAME='A A' \
    GIT_COMMITTER_EMAIL=a@example.com \
    GIT_COMMITTER_NAME='A A'

RUN : \
    && git init . \
    && echo 'print(1    +1)' > t.py \
    && lefthook install \
    && git add .

CMD ["bash", "-xc", "git commit -m test && git status && cat t.py"]
```

```yaml
pre-commit:
  commands:
    autopep8:
      files: git diff --staged --name-only -- '*.py'
      run: autopep8 -i {files}
```

```bash
docker build -t test .
docker run --rm -ti test
```

```console
$ docker run --rm -ti test
+ git commit -m test
Lefthook v0.6.3
RUNNING HOOKS GROUP: pre-commit

  EXECUTE > autopep8

SUMMARY: (done in 0.17 seconds)
✔️  autopep8
[master (root-commit) 2858089] test
 2 files changed, 6 insertions(+)
 create mode 100644 lefthook.yml
 create mode 100644 t.py
+ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   t.py

no changes added to commit (use "git add" and/or "git commit -a")
+ cat t.py
print(1 + 1)
```

**The commit should have been blocked as `autopep8` modified a file**

**Comment by asottile** [comment]
why is this closed? have you addressed this?

**Comment by Arkweid** [comment]
The issue hangs for quite some time, but I have not received any evidence that this is a problem for a wide range of users.
In fact a lot of users just do something like that for fixers:
```
run: rubocop -a && git add
```

**Comment by asottile** [comment]
there's a very clear reproduction in the original issue

**Comment by thieman** [comment]
I'm confused, is your command returning a 0 exit code? If so then I'm not sure what lefthook could possibly do in this situation and it seems correct for it to show the hook as passing.

**Comment by asottile** [comment]
it can detect that files in the index are changed as other hook frameworks do

**Comment by thieman** [comment]
That seems like a pretty big assumption on lefthook's part, though. Most of these tools have exit code configuration for this exact reason (autopep8 included) and I'm not sure why we'd want to duplicate that configuration in lefthook.

**Comment by asottile** [comment]
autopep8 only recently added such an option, take [`yapf`](https://github.com/google/yapf) then instead

**Comment by thieman** [comment]
https://github.com/google/yapf#return-codes

**Comment by asottile** [comment]
right, yapf considers formatting files a "successful run of the program"

**Comment by thieman** [comment]
But you'd run it with `--diff` for a hook, right? Or am I misunderstanding

> If --diff is supplied, YAPF returns zero when no changes were necessary, non-zero otherwise (including program error). You can use this in a CI workflow to test that code has been YAPF-formatted.

**Comment by asottile** [comment]
in my experience, probably not -- you'd want the hook to just fix it for you

**Comment by thieman** [comment]
I think I'm starting to understand you, but you want more than for lefthook to just continue on, right? Sounds like what you're advocating for is:

1. Fixer fixes a bunch of stuff
2. Then you need to `git add` those changes
3. Then you need to either make a new commit or amend the previous one
4. Once all that's done, your commit happily continues on its way to the remote

Is that right? If so, still seems like we're expecting quite a bit of magic to happen in this case.

My previous experience (which may not be optimal) was more like:

1. The fixer fixes the files
2. But then the hook fails and stops execution
3. You're now back in the shell, where you need to add the files and figure out the commit history yourself

**Comment by asottile** [comment]
I don't particularly care what lefthoook does because I'm not going to use it, I created the issue as a comparison issue against (in particular) [pre-commit](https://pre-commit.com)

the second numbered list is what I consider correct (not giving the user a chance to fix the tool output seems not-the-right-thing in the first numbered list)

but again, I don't particularly care either way what lefthoook does :man_shrugging:

**Comment by thieman** [comment]
Actually, if you keep continuing on, you have another problem. Your fixer just changed the files, so now the results of your previous runs are invalid. So you need to start _all_ of the hooks over again to re-check. Right?

**Comment by asottile** [comment]
yes, that's also correct (and a potential argument for the second numbered list)

**Comment by thieman** [comment]
I think I got confused a few comments ago by "you'd want the hook to just fix it for you" and I went off in totally the wrong direction, let me try to reset.

I think you're right and that, given how much of the ecosystem works currently, most users will expect the hook to fail and stop execution if a fixer changes files. I'm seeing a pattern in a few of the fixers I'm looking at, particularly `black` and `gofmt` which are both very popular, that they'll do _one_ of the following, but not both:

1. Fix files, and return 0 unless there was an error
2. Check files without fixing them, and return 1 if any changes would be made

Neither of those are particularly useful given how lefthook currently operates. If you write a hook for 1, lefthook will continue your commit leaving the new changes behind. If you write a hook for 2, you have to manually run the fixer under fixing mode.

A better flow would be:

1. Always write fixer hooks assuming operating mode 1 (fixes files, returns 0 unless error)
2. After all user hooks are executed, lefthook fails the hook if there are any unstaged changes in the index

My wording of 2 might be slightly off but I think that's the gist.

@asottile do you not agree with this summary of current and expected behavior?

**Comment by asottile** [comment]
:+1:
