### ISSUE TITLE
where should I report security issues?

### ISSUE THREAD

**Issue by asottile** [Arkweid/lefthook#61]
unless you want me to just make a github issue CC @Arkweid

**Comment by Arkweid** [comment]
thank you @asottile
You can report it:
telegram: @Arkweid
keybase:  arkweid@evilmartians.com
trwitter private conversations: @Arkweid
email: arkweid@evilmartians.com

**Comment by asottile** [comment]
emailed you a minimal reproduction of the vulnerability

**Comment by Arkweid** [comment]
Got it.

**Comment by asottile** [comment]
Can you update me here when a CVE is posted and when the solution is released -- thanks!

**Comment by Arkweid** [comment]
Yep, no problem.

**Comment by asottile** [comment]
any updates on this? it's been 90+ days (a pretty typical responsible disclosure period)

**Comment by Arkweid** [comment]
Just waiting a batch of features/fixes to release new version. It soon, I hope -_-

**Comment by Arkweid** [comment]
@asottile Sorry, I forgot to inform you about. The issue fixed in 0.6.4

**Comment by asottile** [comment]
fwiw, github just released a bunch of tools for making security advisories -- it's easy to grab a CVE number directly from github now 👍

**Comment by asottile** [comment]
(which would put an automatic advisory here: https://github.com/Arkweid/lefthook/security/advisories)

**Comment by Arkweid** [comment]
Nice point!
