### ISSUE TITLE
More compact output for skipped commands

### ISSUE THREAD

**Issue by perifer** [Arkweid/lefthook#62]
I have a bunch of commands in post-merge that are rarely run. I was thinking if the output could be made more compact since the info here is not super important to show every time a merge is done.

Throwing out some ideas:

* less whitespace
* lowercase instead of uppercase
* try to put info in one line
* skip output all together for skipped command and just summarise them at the end

This is an example of how it looks today:

```
Lefthook v0.6.3
RUNNING HOOKS GROUP: post-merge

  EXECUTE > command1
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > command2
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > command3
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > command4
(SKIP. NO FILES FOR INSPECTING)

  EXECUTE > command5
(SKIP. NO FILES FOR INSPECTING)

SUMMARY: (SKIP EMPTY)
```

**Comment by Arkweid** [comment]
Similar as #78
