### ISSUE TITLE
Add documentation for Python environment

### ISSUE THREAD

**Issue by orsinium** [Arkweid/lefthook#63]
Thank you for the nice tool. I've made a simple wrapper to install lefthook from python environment:
https://github.com/life4/lefthook

1. Please, check it out.
1. Should we make installation instruction for the Python environment as well?

@Arkweid, I can give you access to the repository and PyPI to let you have control over it.

**Comment by Arkweid** [comment]
Awesome, thank you @orsinium! I will check it :+1:

**Comment by orsinium** [comment]
> Is versioning possible with this wrapper, or it always installs the latest version?

It just tries other commands from docs:

https://github.com/life4/lefthook/blob/master/lefthook/_core.py#L6-L11

I thought about some versioning, but haven't noticed config specification versioning and conclude that lefthook always follow backward compatibility. Installing always the latest version allows us to avoid this wrapper actualization on every release.
