### ISSUE TITLE
Import existing hook script when installing

### ISSUE THREAD

**Issue by klauern** [Arkweid/lefthook#75]
I use [`awslabs/git-secrets`](https://github.com/awslabs/git-secrets) as a pre-install hook for all Git clone operations, and I would like to maintain having that when using Lefthook.  In looking how `lefthook install` works, it won't take the existing hooks and import it, and I'm not sure how to enable a global set of hooks that will be run.

I'd prefer if there were an option to not replace my `.git/hooks` with lefthook's, and instead append the lefthook configuration.  Barring that, I'd like to see some options for global hooks that could be installed or set up once in your `$HOME/.lefthook` dir, so it could be included by default for all `lefthook` operations.

**Comment by Arkweid** [comment]
It sound very close to `shared configs` #30

**Comment by Arkweid** [comment]
Done https://github.com/Arkweid/lefthook/blob/master/docs/full_guide.md#extends-option
