### ISSUE TITLE
postinstall fails when using in monorepo

### ISSUE THREAD

**Issue by sHooKDT** [Arkweid/lefthook#85]
I'm trying to use lefthook in monorepo. Config is located in root and lefthook is installed there, but on postinstall (literally - when I install any package to the subproject) it's trying to access lefthook binary in the inner node_modules.
![image](https://user-images.githubusercontent.com/5585758/68216544-dc0d1180-0002-11ea-82f4-5c3eff531643.png)
You can see on the screenshot, lefthook is executed from `paxshop-2.0/node_modules/@arkweid/lefthook` but trying to call `paxshop-2.0/packages/paxshop/node_modules/@arkweid/lefthook/bin/lefthook-mac`

It causes yarn to fail and not writing changes to `package.json`.

**Comment by Arkweid** [comment]
Monorepos not supported yet :(

**Comment by sHooKDT** [comment]
I don't see any issues with exactly this problem.
Are you planning to support them?
It's okay to not have special features like this one https://github.com/Arkweid/lefthook/issues/72, but I believe the issue with postinstall could be fixed with just a small effort.

**Comment by Arkweid** [comment]
Yes. But right now I can't do that because my current project consume all my time.
If you make a PR to fix this problem, I will merge it.

**Comment by Arkweid** [comment]
Should be fixed in 0.6.4 release @sHooKDT
