### ISSUE TITLE
sh executable file not found

### ISSUE THREAD

**Issue by seniorquico** [Arkweid/lefthook#91]
On Windows 10 with lefthook 0.6.5, I get the following error:

```
exec: "sh": executable file not found in %PATH%
```

It even occurs when running `lefthook version`.

**Comment by Arkweid** [comment]
Try to run in with mingw terminal(https://gitforwindows.org/ or similar) or inside `Windows Subsystem for Linux (WSL)`

**Comment by seniorquico** [comment]
Yes, I can get it to work if I get a copy of `sh` and place it on my path. Do you expect, short- or long-term, that `sh` will be a requirement for running lefthook on Windows?

**Comment by Arkweid** [comment]
Yep, for now it a requirement. With `sh` users have an ability to write simple scripts, comething like that:
```
eslint:
    glob: "*.{js,ts}"
    run: yarn eslint {staged_files} && git add
```

**Comment by Arkweid** [comment]
If anyone has tips on how to support the `sh` syntax for windows, I will be glad to know about it.
