### ISSUE TITLE
Documentation Request:

### ISSUE THREAD

**Issue by brandondrew** [Arkweid/lefthook#92]
## Background info ##

I'm a former Overcommit user, and while I love the idea of something like Overcommit, it bothered me that _it had to own your entire `.git/hooks` directory._  It could not play well with other scripts you wanted to put in there.  There was one other egregious problem, but this is one of the main reasons I no longer use it.

## Request ##

Could you please include in your README (or at least in your comparison with other tools) whether this is the case with Lefthook?  Do I need to cede complete control of my `.git/hooks` directory to Lefthook?  Or can it coexist with other scripts?

**Comment by Arkweid** [comment]
Hi @brandondrew
Lefthook play well with other scripts in `.git/hooks` directory. It not take own on `.git/hooks` directory. Lefthook only add hooks from `lefthook.yml`. If you describe only one hook, for example `pre-commit`, so only one `pre-commit` file will be added into `.git/hooks` directory(and `prepare-commit-msg` too, for config sync purposes)

**Comment by brandondrew** [comment]
Excellent! Thank you!
